#!/bin/sh
#generate json and others
jq -Rsnc '
  {"dict":
    [inputs
     | . / "\n"
     | (.[] | select(length > 0) | . / ",") as $input
     | {"ar": $input[0], "en": $input[1], source: $input[2]}]}
' <techdict.csv >> temp.json
jq -c . < temp.json > techdict.json
rm temp.json


